# Generated by Django 4.0.5 on 2022-06-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://nolabelatthetable.com/wp-content/uploads/2018/01/IMAGE-COMING-SOON-300x300.png', max_length=500),
        ),
    ]
